### getAll
GET https://cse-341-project1-6mjg.onrender.com/contacts 


### getSingle
GET https://cse-341-project1-6mjg.onrender.com/contacts/690e2c49620a88ee5310034c

### createContact
POST https://cse-341-project1-6mjg.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Emeka",
    "lastName": "Ohiaeri",
    "email": "emeorie@gmail.com",
    "favoriteColor":"orange",
    "birthday":"13-2-1993"
}

### deleteContact
DELETE https://cse-341-project1-6mjg.onrender.com/contacts/690e2c49620a88ee5310034c HTTP/1.1
